class wgeometry {
	unsigned 	n_box;
	unsigned 	n_cyl;
	unsigned 	n_hex;
	unsigned 	n_sph;
	unsigned 	n_primitives;
	unsigned 	n_transforms;
	unsigned 	outer_cell;
	unsigned 	n_materials;
	unsigned 	n_isotopes;
	unsigned 	fissile_flag;
	unsigned * 	material_num_list;
	unsigned * 	cell_num_list;
public:
	 wgeometry();
	~wgeometry();
	unsigned get_minimum_cell();
	unsigned get_maximum_cell();
	unsigned get_primitive_count();
	unsigned get_transform_count();
	unsigned add_primitive();
	unsigned add_primitive(int , unsigned  ,std::vector<float>,std::vector<float>,std::vector<float> );
	void update();
	void print_summary();
	void print_all();
	void set_outer_cell(unsigned);
	unsigned get_outer_cell();
	void add_material(unsigned , unsigned, unsigned , float, std::vector<unsigned> , std::vector<float> );
	int check();
	unsigned get_outer_cell_dims(float*);
	unsigned get_material_count();
	void make_material_table();
	void get_material_table(unsigned*,unsigned*,unsigned**,unsigned**,float**);
	void print_materials_table();
	unsigned check_fissile();
	unsigned add_transform(unsigned);
	unsigned add_transform(unsigned, unsigned, float, float, float, float, float);
	unsigned add_transform(unsigned, unsigned, unsigned, float, float, float, float, float);
	void make_hex_array(unsigned, int, float, float, float, unsigned);
	void delete_primitive(unsigned);
	void delete_transform(unsigned,unsigned);
	std::vector<primitive>   	primitives;
	std::vector<material_def>	materials;
	std::vector<unsigned>		isotopes;
	std::string 				isotope_list;
	unsigned *	isotope_list_array;
	unsigned *	material_list_array;
	float * 	concentrations_matrix;
	float * 	awr_list;
};